---
- hosts: all
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Create security group. #to naknadno pokazem kot ocija da lahko pa nadgradijo scope.
      amazon.aws.ec2_security_group:
        name: "web-app-sec"
        description: "Sec group for app web-app"
        region: "us-west-2"
        access_key: "sdafrgeg3wfw"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: result_sec_group

    - name: Create an example.com A record with value 127.0.0.1
      inwx.collection.dns:
        domain: example.com
        type: A
        value: 127.0.0.1
        username: test_user
        password: test_password

    - name: Ensure that the desired snmp strings are present.
      cisco.ios.ios_config:
        lines:
          - "{{ some_variable }}"


    - name: As a single dependency
      ansible.builtin.dnf:
        name:
          - git
          - python3
        state: present
      become: true
 
    - name: In a loop
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - python3
      become: true